<a href="https://colab.research.google.com/github/Akshaya-Rajesh/deeplearning.ai/blob/master/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#                  **Broadcasting in Python** 


The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 

There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

**Calculate the total % of calories from carbohydrate, protein and fat for each food items.**
            
Nutrients (Apples, Beef, Eggs, Potatoes)

Carbohydrate  (56.0, 0.0, 4.4, 68.0)

Protein  (1.2, 104.0, 52.0, 8.0)

Fat  (1.8, 135.0, 99.0, 0.9)


In [7]:
import numpy as np

#define a matrix with values 
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])

print(A)
print(A.shape)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
(3, 4)


In [6]:
# find total calories for each food items.
cal = A.sum(axis=0)   # axis=0 means vertical sum

print(cal)
print(cal.shape)

[ 59.  239.  155.4  76.9]
(4,)


In [5]:
# find percntage of calories
percentage = 100*A/cal.reshape(1,4)     # this is python broadcasting. where a matrix of shape (3,4) is divided by a matrix of shape (1,4)

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


More Examples

In [13]:
A = np.array([[1,2,3]])
print(A)
print("Shape of A is "+ str(A.shape))

#add 100 to each element
A+=100
print(A)

[[1 2 3]]
Shape of A is (1, 3)
[[101 102 103]]


In [14]:
A = np.array([[1],[2],[3]])
print(A)
print("Shape of A is "+ str(A.shape))

#add 100 to each element
A+=100
print(A)

[[1]
 [2]
 [3]]
Shape of A is (3, 1)
[[101]
 [102]
 [103]]


In [15]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("Shape of A is "+ str(A.shape))

#add 100 to each element
A+=100
print(A)

[[1 2 3]
 [4 5 6]]
Shape of A is (2, 3)
[[101 102 103]
 [104 105 106]]


In [16]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("Shape of A is "+ str(A.shape))

A+=[100,200,300]
print(A)

[[1 2 3]
 [4 5 6]]
Shape of A is (2, 3)
[[101 202 303]
 [104 205 306]]


In [18]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("Shape of A is "+ str(A.shape))

A+=[[100],[200]]
print(A)

[[1 2 3]
 [4 5 6]]
Shape of A is (2, 3)
[[101 102 103]
 [204 205 206]]
