<a href="https://colab.research.google.com/github/Akshaya-Rajesh/deeplearning.ai/blob/master/Rank_1_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rank 1 Arrays

**Arrays of the shape (n,) are called rank 1 arrays.** 

Any given array object has a rank, which is the number of "dimensions" or "axes" it has.
For example, a point in 3D space [1, 2, 1] is an array of rank 1 - it has one dimension. That dimension has a length of 3.


In [1]:
import numpy as np

a = np.random.randn(5)  # 5 random gaussian variables stored in array a
print(a)

[ 1.06667886 -0.38917586 -0.17011221  2.31052626 -0.80360739]


In [2]:
print(a.shape)  # rank 1 array

(5,)


In [14]:
# wont work as expected beacause it is a rank 1 array
# Transpose will looks like the same
print(a.T)

print(np.dot(a,a.T))

[[ 0.45269717 -1.6636304  -0.07486187  0.1835472  -1.2602481 ]]
[[ 0.20493473 -0.75312078 -0.03388976  0.0830913  -0.57051075]
 [-0.75312078  2.76766612  0.12454249 -0.3053547   2.09658706]
 [-0.03388976  0.12454249  0.0056043  -0.01374069  0.09434454]
 [ 0.0830913  -0.3053547  -0.01374069  0.03368957 -0.23131501]
 [-0.57051075  2.09658706  0.09434454 -0.23131501  1.58822528]]


In [7]:
# use this convention instead
a = np.random.randn(5,1)
print(a)

[[ 0.45269717]
 [-1.6636304 ]
 [-0.07486187]
 [ 0.1835472 ]
 [-1.2602481 ]]


In [13]:
print(a.T)
print("\n")
print(np.dot(a,a.T))

[[ 0.45269717 -1.6636304  -0.07486187  0.1835472  -1.2602481 ]]


[[ 0.20493473 -0.75312078 -0.03388976  0.0830913  -0.57051075]
 [-0.75312078  2.76766612  0.12454249 -0.3053547   2.09658706]
 [-0.03388976  0.12454249  0.0056043  -0.01374069  0.09434454]
 [ 0.0830913  -0.3053547  -0.01374069  0.03368957 -0.23131501]
 [-0.57051075  2.09658706  0.09434454 -0.23131501  1.58822528]]


**Or Use the following conventions.**

*Reshape the array*: a = a.reshape(5,1)

*Use assertion* : assert(a.shape == (5,1))